/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
  cacheDirectory: "./node_modules/.cache/remix",
  ignoredRouteFiles: ["**/.*", "**/*.css", "**/*.test.{js,jsx,ts,tsx}"],
  serverDependenciesToBundle: [
		/^unified.*/,
		/^property.*/,
		/^unist.*/,
		/^hast.*/,
		/^bail.*/,
		/^stringify-entities*/,
		/^parse-entities*/,
		/^mdast.*/,
		/^space.*/,
		/^comma.*/,
		/^micromark.*/,
		/^character.*/,
		/^is-decimal*/,
		/^is-hexadecimal*/,
		/^is-alphanumerical*/,
		/^is-alphabetical*/,
		/^trim-lines*/,
		/^rehype.*/,
		/^remark.*/,
		/^react-markdown$/,
		/^trough.*/,
		/^vfile.*/,
		/^mermaid.*/,
		/^khroma*/,
		/^d3*/,
		/^lodash-es*/,
		/^dagre-d3-es.*/,
		/^robust-predicates*/,
		/^internmap.*/,
	],
};